
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O master, dependiendo de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # O la versión que estés utilizando
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # La rama donde se desplegará el contenido
          folder: dist # La carpeta que contiene los archivos a desplegar
          clean: true # Limpia la rama antes de desplegar
